import type { AssumptionsInput, ProjectInput } from "./calculations";

export const defaultAssumptions: AssumptionsInput = {
  kitchenDefault: 0,
  bathroomDefault: 0,
  flooringDefault: 0,
  decoratingDefault: 0,
  plumbingDefault: 0,
  electricalDefault: 0,
  gardenDefault: 0,
  restOfHouseDefault: 0,
  miscDefault: 0,
  renovationCostPerSqFt: 0.082,
  kitchenRenoCostPerSqFt: 66.36,
  bathroomRenoCostPerSqFt: 51.03,
  flooringCostPerSqFt: 1550 / 915,
  plasteringCostPerSqFt: 385 / 35,
  skipCost: 240,
  skipCoverageSqFt: 915,
  acquisitionCostPerSqFt: 205.57,
  plumbingDayRate: 385,
  electricianDayRate: 385,
  decoratorDayRate: 250,
  plastererDayRate: 300,
  lightTradeDays: 0.5,
  mediumTradeDays: 1,
  heavyTradeDays: 2,
  mortgageCostPerMonth: 279,
  councilTaxPerMonth: 190,
  utilitiesPerMonth: 113,
  insurancePerMonth: 10,
  stampDutyDefault: 0,
  purchaseLegalFees: 1200,
  survey: 500,
  brokerFee: 199,
  lenderValuationFee: 0,
  mortgageArrangementFee: 0,
  saleLegalFees: 1000,
  epc: 0,
  stagingPhotography: 0,
  mortgageExitFee: 0,
  estateAgentFeeMode: "PERCENTAGE",
  estateAgentFixedFee: 0,
  estateAgentPercentage: 1.2,
  contingencyPercentage: 10,
};

export const ericaDriveProject: ProjectInput = {
  name: "Erica Drive",
  addressOrArea: "Erica Drive",
  propertyType: "BUNGALOW",
  bedrooms: 2,
  bathrooms: 1,
  internalSqFt: 915,
  kitchenSqFt: 71.53,
  bathroomSqFt: 34.76,
  flooringSqFt: null,
  plasteringSqFt: null,
  plumbingHours: null,
  electricalHours: null,
  askingPrice: 185000,
  estimatedMarketValue: 185000,
  estimatedSalePrice: 220000,
  targetPurchasePrice: null,
  actualPurchasePrice: 185000,
  conditionLevel: "MEDIUM_COSMETIC",
  needsKitchen: true,
  needsBathroom: true,
  needsFlooring: false,
  needsDecorating: true,
  needsMinorPlumbing: false,
  needsMinorElectrical: false,
  needsGardenWork: false,
  plumbingLevel: "NONE",
  electricalLevel: "NONE",
  decoratingLevel: "NONE",
  plasteringLevel: "NONE",
  estimatedHoldingMonths: 9,
  financeType: "MORTGAGE",
  depositAmount: null,
  mortgageInterestRate: null,
  mortgageTermYears: null,
  targetRoiPercent: null,
  targetProfit: null,
  stampDuty: null,
  survey: 500,
  purchaseLegalFees: 1200,
  brokerFee: 199,
  lenderValuationFee: 0,
  mortgageArrangementFee: 0,
  kitchenCost: 4746.88,
  bathroomCost: 1773.6,
  restOfHouseCost: null,
  miscCost: null,
  contingencyPercentage: 0,
  mortgageCostPerMonth: 279,
  councilTaxPerMonth: 190,
  utilitiesPerMonth: 113,
  insurancePerMonth: 10,
  estateAgentFeeMode: "PERCENTAGE",
  estateAgentFixedFee: null,
  estateAgentPercentage: 1.2,
  saleLegalFees: 1000,
  epc: 0,
  stagingPhotography: 0,
  mortgageExitFee: null,
  capitalGainsTax: 0,
};

export const ericaDriveCostItems = [
  {
    name: "Kitchen renovation allowance",
    tag: "Kitchen",
    amount: 4746.88,
    purchased: false,
    supplier: null,
    purchaseUrl: null,
    notes: "Allowance from Erica Drive model.",
  },
  {
    name: "Bathroom renovation allowance",
    tag: "Bathroom",
    amount: 1773.6,
    purchased: false,
    supplier: null,
    purchaseUrl: null,
    notes: "Allowance from Erica Drive model.",
  },
  {
    name: "Full house flooring quote",
    tag: "Flooring",
    amount: 1550,
    purchased: false,
    supplier: null,
    purchaseUrl: null,
    notes: "Quote covers 915 sq ft.",
  },
  {
    name: "Brilliant white paint allowance",
    tag: "Decorating",
    amount: 75.03,
    purchased: false,
    supplier: null,
    purchaseUrl: null,
    notes: "915 sq ft x £0.082 per sq ft.",
  },
  {
    name: "Skip hire",
    tag: "Waste",
    amount: 240,
    purchased: false,
    supplier: null,
    purchaseUrl: null,
    notes: "One skip allowance for 915 sq ft renovation.",
  },
];
