import type { AssumptionsInput, ProjectInput } from "./calculations";

export const defaultAssumptions: AssumptionsInput = {
  kitchenDefault: 0,
  bathroomDefault: 0,
  flooringDefault: 0,
  decoratingDefault: 0,
  plumbingDefault: 0,
  electricalDefault: 0,
  gardenDefault: 0,
  restOfHouseDefault: 0,
  miscDefault: 0,
  renovationCostPerSqFt: 0.082,
  kitchenRenoCostPerSqFt: 66.36,
  bathroomRenoCostPerSqFt: 51.03,
  flooringCostPerSqFt: 1550 / 915,
  plasteringCostPerSqFt: 385 / 35,
  skipCost: 240,
  skipCoverageSqFt: 915,
  acquisitionCostPerSqFt: 205.57,
  plumbingDayRate: 385,
  electricianDayRate: 385,
  decoratorDayRate: 250,
  plastererDayRate: 300,
  lightTradeDays: 0.5,
  mediumTradeDays: 1,
  heavyTradeDays: 2,
  mortgageCostPerMonth: 279,
  councilTaxPerMonth: 190,
  utilitiesPerMonth: 113,
  insurancePerMonth: 10,
  stampDutyDefault: 0,
  purchaseLegalFees: 1200,
  survey: 500,
  brokerFee: 199,
  lenderValuationFee: 0,
  mortgageArrangementFee: 0,
  saleLegalFees: 1000,
  epc: 0,
  stagingPhotography: 0,
  mortgageExitFee: 0,
  estateAgentFeeMode: "PERCENTAGE",
  estateAgentFixedFee: 0,
  estateAgentPercentage: 1.2,
  contingencyPercentage: 10,
};

export const ericaDriveProject: ProjectInput = {
  name: "Erica Drive",
  addressOrArea: "Erica Drive",
  propertyType: "BUNGALOW",
  bedrooms: 2,
  bathrooms: 1,
  internalSqFt: 915,
  kitchenSqFt: 71.53,
  bathroomSqFt: 34.76,
  flooringSqFt: null,
  plasteringSqFt: null,
  plumbingHours: null,
  electricalHours: null,
  askingPrice: 185000,
  estimatedMarketValue: 185000,
  estimatedSalePrice: 220000,
  targetPurchasePrice: null,
  actualPurchasePrice: 185000,
  conditionLevel: "MEDIUM_COSMETIC",
  needsKitchen: true,
  needsBathroom: true,
  needsFlooring: false,
  needsDecorating: true,
  needsMinorPlumbing: false,
  needsMinorElectrical: false,
  needsGardenWork: false,
  plumbingLevel: "NONE",
  electricalLevel: "NONE",
  decoratingLevel: "NONE",
  plasteringLevel: "NONE",
  estimatedHoldingMonths: 9,
  financeType: "MORTGAGE",
  depositAmount: null,
  mortgageInterestRate: null,
  mortgageTermYears: null,
  targetRoiPercent: null,
  targetProfit: null,
  stampDuty: null,
  survey: 500,
  purchaseLegalFees: 1200,
  brokerFee: 199,
  lenderValuationFee: 0,
  mortgageArrangementFee: 0,
  kitchenCost: 4746.88,
  bathroomCost: 1773.6,
  restOfHouseCost: null,
  miscCost: null,
  contingencyPercentage: 0,
  mortgageCostPerMonth: 279,
  councilTaxPerMonth: 190,
  utilitiesPerMonth: 113,
  insurancePerMonth: 10,
  estateAgentFeeMode: "PERCENTAGE",
  estateAgentFixedFee: null,
  estateAgentPercentage: 1.2,
  saleLegalFees: 1000,
  epc: 0,
  stagingPhotography: 0,
  mortgageExitFee: null,
  capitalGainsTax: 0,
};

const costItem = (
  tag: string,
  name: string,
  amount: number,
  options: { purchaseUrl?: string | null; notes?: string | null } = {},
) => ({
  name,
  tag,
  amount,
  purchased: true,
  supplier: null,
  purchaseUrl: options.purchaseUrl ?? null,
  notes: options.notes ?? "Imported from Erica Dr Reno supply sheet.",
});

export const ericaDriveStarterItemNames = [
  "Kitchen renovation allowance",
  "Bathroom renovation allowance",
  "Full house flooring quote",
  "Brilliant white paint allowance",
  "Skip hire",
];

export const ericaDriveCostItems = [
  costItem("Kitchen", "End panel (H2400 W610)", 376),
  costItem("Kitchen", "Base unit W1000mm", 189),
  costItem("Kitchen", "Standard Wall Clad on end panel (H960 W360)", 130),
  costItem("Kitchen", "Standard Wall cabinet W400 D320", 294),
  costItem("Kitchen", "Base unit W400mm", 208),
  costItem("Kitchen", "Base unit W1000mm (alt)", 391),
  costItem("Kitchen", "Base unit W300mm", 101),
  costItem("Kitchen", "Standard Wall cabinet W1000 D320", 182),
  costItem("Kitchen", "Standard Wall cabinet W900 D320", 178),
  costItem("Kitchen", "60cm Integrated Hood (standard chimney hood)", 155, {
    purchaseUrl: "https://www.appliancesdirect.co.uk/p/eiqchim60sc/electriq-eiqchim60sc-60cm-chimney-hood",
  }),
  costItem("Kitchen", "Base unit W400mm (second)", 250),
  costItem("Kitchen", "Single Oven Housing with Pan Drawers", 600),
  costItem("Kitchen", "Standard Wall cabinet W500 D320", 101),
  costItem("Kitchen", "Standard End support panel H870 W590", 122),
  costItem("Kitchen", "Base unit W600mm", 116),
  costItem("Kitchen", "Straight Cornice & pelmet L2400", 114),
  costItem("Kitchen", "End panel (H2400 W610) additional", 94),
  costItem("Kitchen", "End panel (H870 W590)", 61),
  costItem("Kitchen", "End panel (H960 W360)", 65),
  costItem("Kitchen", "Plinth", 156),
  costItem("Kitchen", "Plinth strip", 32),
  costItem("Kitchen", "Kitchen Worktop L3000", 396),
  costItem("Kitchen", "Edging tape L10m", 11),
  costItem("Kitchen", "Dishwasher Fascia", 54),
  costItem("Kitchen", "Worktop joining bolts pack", 6),
  costItem("Kitchen", "Joining biscuits pack", 6.57),
  costItem("Kitchen", "Round Pull Handle pack of 2", 72),
  costItem("Kitchen", "Dishwasher integrated", 300, {
    purchaseUrl: "https://www.appliancesdirect.co.uk/p/din15x20/beko-din15x20--built-in-dishwasher",
  }),
  costItem("Kitchen", "Ceramic hob 59cm", 199, {
    purchaseUrl: "https://www.appliancesdirect.co.uk/p/eiqc60touch/electriq-eiqc60touch-4-zone-ceramic-hob-hob",
  }),
  costItem("Kitchen", "Integrated Frost Free Fridge Freezer", 400, {
    purchaseUrl: "https://www.appliancesdirect.co.uk/p/eqintff7030hve/electriq-eqintff7030hve--built-in-fridge-freezer",
  }),
  costItem("Kitchen", "Oven", 150, {
    purchaseUrl: "https://www.appliancesdirect.co.uk/p/eqovenm1ss/electriq-eqovenm1ss--electric-oven",
  }),
  costItem("Kitchen", "Kitchen delivery charge", 75),
  costItem("Kitchen", "Kitchen reduction", -669.09, {
    notes: "15% reduction from Erica Dr Reno supply sheet.",
  }),
  costItem("Bathroom", "Rimless Slim Round Toilet set", 0),
  costItem("Bathroom", "Vertical Towel radiator", 145.59),
  costItem("Bathroom", "Shower tray 1000x760", 200),
  costItem("Bathroom", "Electric Shower 8.5kW", 185),
  costItem("Bathroom", "Wall installation kit", 0),
  costItem("Bathroom", "Wall-mounted Bathroom Vanity unit", 225),
  costItem("Bathroom", "Rectangular Vanity Basin", 95),
  costItem("Bathroom", "Vanity Tap", 130),
  costItem("Bathroom", "Shower trap", 36),
  costItem("Bathroom", "Waterproof board 1200x600", 0),
  costItem("Bathroom", "Backer board 2400x600", 0),
  costItem("Bathroom", "Splashwall H-Joint Panel", 15),
  costItem("Bathroom", "Splashwall MDF Tongue & Groove Panel", 110),
  costItem("Bathroom", "Splashwall 2 panel Wallpanel kit", 650),
  costItem("Bathroom", "Comfort height Close-coupled Toilet set", 260),
  costItem("Bathroom", "Shower doors", 282),
  costItem("Bathroom", "Shower tray 1000x760 additional", 180),
  costItem("Bathroom", "Bathroom delivery charge", 35),
  costItem("Bathroom", "Bathroom reduction", -307.74, {
    notes: "15% reduction from Erica Dr Reno supply sheet.",
  }),
  costItem("Rest of house", "Carpet supply and fit", 1546),
  costItem("Rest of house", "Paint", 92.5),
  costItem("Rest of house", "Internal doors including handles", 250),
  costItem("Rest of house", "Extractor fan and ducting in bathroom", 0),
  costItem("Misc", "Skip", 240),
  costItem("Misc", "Labour cost", 385),
  costItem("Misc", "Masonry bolster", 9.99),
  costItem("Misc", "8x floorboards & 8x 2x4 timber", 31.9),
  costItem("Misc", "Supply sheet rounding adjustment", 0.01, {
    notes: "One-penny adjustment so itemised rows match the supply sheet headline total of £9,711.73.",
  }),
];
